import { SchemeMatch } from '../types';

export const MOCK_SCHEMES: SchemeMatch[] = [
  {
    id: 'nssfp',
    code: 'NSSFP',
    nameEn: 'National Solar Science Fellowship Programme',
    nameHi: 'राष्ट्रीय सौर विज्ञान फेलोशिप कार्यक्रम',
    ministryEn: 'Ministry of New and Renewable Energy',
    ministryHi: 'नवीन और नवीकरणीय ऊर्जा मंत्रालय',
    descriptionEn: 'The “National Solar Science Fellowship Programme” of the Ministry of New & Renewable Energy was launched in February 2011. The programme is meant for an Indian Scientist desirous of working in the forefront areas of solar energy science, engineering, and technology with a focus on science, technology, and product development in collaboration with selected prestigious institutions in India. The aim of the National Solar Science Fellowship Programme is to provide a platform to top quality scientists and engineers in the area of solar energy research, to use and expand the resources available at the identified schools/ institutions in the country and abroad to address the complex problems of solar energy utilization for various end uses including power generation.',
    descriptionHi: 'नवीन एवं नवीकरणीय ऊर्जा मंत्रालय का "राष्ट्रीय सौर विज्ञान फेलोशिप कार्यक्रम" फरवरी 2011 में शुरू किया गया था। यह कार्यक्रम सौर ऊर्जा विज्ञान, इंजीनियरिंग और प्रौद्योगिकी के क्षेत्र में अनुसंधान एवं विकास कार्य करने वाले भारतीय वैज्ञानिकों के लिए है।',
    compatibilityPercentage: 96.0,
    categoryBadge: 'FELLOWSHIP & RESEARCH',
    tags: ['Education & Learning', 'Science & Technology', 'Renewable Energy'],
    financials: {
      grantSubsidyPercentage: 100,
      maxGrantAmount: 3600000,
      loanPercentage: 0,
      promoterMarginPercentage: 0,
      collateralRequired: false,
    },
    requiredDocuments: ['DOC_AADHAAR', 'DOC_MARKSHEET', 'DOC_PROJECT_REPORT', 'DOC_CASTE'],
    verifiedDocuments: ['DOC_AADHAAR', 'DOC_MARKSHEET'],
    missingDocuments: ['DOC_PROJECT_REPORT'],
    eligibilityHighlights: [
      'Fellowship grant of ₹1,00,000/month + ₹5,00,000/year research contingency',
      'Open to Indian Scientists & Engineers with Ph.D. or M.Tech./M.S.',
      'Collaboration with premier institutions (IITs, IISc, NITs, Central Labs)',
    ],
    nodalAgency: 'Ministry of New & Renewable Energy (MNRE), Govt of India',
    benefits: [
      'Monthly Fellowship Grant of ₹1,00,000 per month for selected scientists and engineers.',
      'Annual Research Contingency Grant of up to ₹5,00,000 per year for project equipment, consumables, and international publications.',
      'Institutional overhead support grant to host universities and national laboratories.',
      'Tenure of fellowship for 3 years, extendable up to 2 additional years based on performance review.',
      'Access to top scientific infrastructure across premier institutions in India and abroad.',
    ],
    eligibilityCriteria: [
      'Applicant must be an Indian citizen.',
      'Must possess a Ph.D. or M.Tech./M.S. in engineering, science, or allied disciplines.',
      'Must have demonstrated research & development track record in the forefront areas of solar energy.',
      'Candidates from all categories (General, OBC, SC, ST, EWS) are eligible to apply.',
      'Identified host institution in India willing to provide laboratory facilities and research environment.',
    ],
    applicationProcess: [
      'Step 1: Obtain the official application proforma from the Ministry of New & Renewable Energy (MNRE) portal (mnre.gov.in).',
      'Step 2: Prepare a comprehensive research proposal focusing on solar energy science, engineering, or technology.',
      'Step 3: Secure formal endorsement from the Head of the identified host institution in India.',
      'Step 4: Submit the complete application dossier with verified educational degrees, research publications, and identity proofs.',
      'Step 5: Review and shortlisting by the National Solar Science Fellowship Search-cum-Selection Committee, followed by final selection interview.',
    ],
    faqs: [
      {
        question: 'What is the aim of the scheme?',
        answer: 'The aim of the National Solar Science Fellowship Programme is to provide a platform to top quality scientists and engineers in the area of solar energy research, to use and expand the resources available at the identified schools/ institutions in the country and abroad to address the complex problems of solar energy utilization for various end uses including power generation.',
      },
      {
        question: 'Which department has launched this scheme?',
        answer: 'The scheme has been launched by the Ministry of New and Renewable Energy (MNRE), Government of India.',
      },
      {
        question: 'When was this scheme launched?',
        answer: 'The National Solar Science Fellowship Programme was launched in February 2011.',
      },
      {
        question: 'Who is eligible to get the benefits under the scheme?',
        answer: 'The programme is meant for an Indian Scientist desirous of working in the forefront areas of solar energy science, engineering, and technology with a focus on science, technology, and product development in collaboration with selected prestigious institutions in India.',
      },
      {
        question: 'Can a general category applicant be eligible to apply under this scheme?',
        answer: 'Yes, general category applicants are fully eligible to apply under this scheme, along with applicants from all other categories (OBC, SC, ST, EWS), provided they satisfy the technical qualification and research requirements.',
      },
      {
        question: 'What is the minimum qualification required to apply under the scheme?',
        answer: 'Applicants must possess a Ph.D. or an M.Tech./M.S. degree in engineering, science, or allied fields with a demonstrable background and track record of research in the area of solar energy.',
      },
      {
        question: 'Can an M.Tech. or M.S. degree holder candidate be eligible to apply under the scheme?',
        answer: 'Yes, an M.Tech. or M.S. degree holder candidate is eligible to apply under the scheme, provided they possess relevant research competence and background in solar energy science or technology.',
      },
      {
        question: 'Is it mandatory for a candidate to have an appropriate background in academics and experience in R&D in the area of solar energy?',
        answer: 'Yes, it is mandatory for candidates to have an appropriate background in academics and relevant research & development experience in the area of solar energy science and technology.',
      },
      {
        question: 'Will there be any age bar for the candidates to apply under the programme?',
        answer: 'Candidates should ordinarily be below 35-40 years of age at the time of application, with applicable relaxations for reserved categories (SC/ST/OBC/Women/PwD) per Government of India guidelines.',
      },
      {
        question: 'What is the benefit of the scheme?',
        answer: 'The scheme provides a monthly fellowship stipend of ₹1,00,000, an annual research contingency grant of up to ₹5,00,000, overhead support to host institutions, and access to leading national labs and academic networks.',
      },
    ],
    sourcesAndReferences: [
      { title: 'Ministry of New & Renewable Energy (MNRE) Official Portal', url: 'https://mnre.gov.in' },
      { title: 'myScheme Government of India Portal', url: 'https://www.myscheme.gov.in/schemes/nssfp' },
      { title: 'National Institute of Solar Energy (NISE)', url: 'https://nise.res.in' },
    ],
  },
  {
    id: 'pm-egp',
    code: 'PMEGP',
    nameEn: "Prime Minister's Employment Generation Programme (PMEGP)",
    nameHi: "प्रधानमंत्री रोजगार सृजन कार्यक्रम (PMEGP)",
    ministryEn: 'Ministry of MSME / KVIC',
    ministryHi: 'सूक्ष्म, लघु एवं मध्यम उद्यम मंत्रालय (KVIC)',
    descriptionEn: 'Credit-linked capital subsidy scheme designed for setting up new micro-enterprises in manufacturing and services sector.',
    descriptionHi: 'विनिर्माण एवं सेवा क्षेत्रों में नए सूक्ष्म उद्यम स्थापित करने के लिए क्रेडिट-लिंक्ड पूंजी सब्सिडी योजना।',
    compatibilityPercentage: 94.5,
    categoryBadge: 'TOP SUBSIDY MATCH',
    tags: ['Business & Entrepreneurship', 'Financial Services', 'Manufacturing'],
    financials: {
      grantSubsidyPercentage: 35,
      maxGrantAmount: 1750000,
      loanPercentage: 60,
      promoterMarginPercentage: 5,
      subsidizedInterestRate: 8.5,
      moratoriumPeriodMonths: 6,
      collateralRequired: false,
    },
    requiredDocuments: ['DOC_AADHAAR', 'DOC_CASTE', 'DOC_RURAL', 'DOC_INCOME'],
    verifiedDocuments: ['DOC_AADHAAR', 'DOC_CASTE', 'DOC_INCOME'],
    missingDocuments: ['DOC_RURAL'],
    eligibilityHighlights: [
      '35% direct non-refundable capital grant for rural OBC/SC/ST/Women',
      'Only 5% beneficiary own margin required',
      '100% collateral-free under CGTMSE cover',
    ],
    nodalAgency: 'Khadi & Village Industries Commission (KVIC) / DIC Gorakhpur',
    benefits: [
      'Direct non-refundable capital subsidy up to 35% of total project cost (up to ₹17.5 Lakhs for manufacturing).',
      'Only 5% to 10% beneficiary promoter contribution needed.',
      'Bank term loan and working capital coverage up to 90% without third-party guarantee.',
      'Covered under CGTMSE credit guarantee with zero collateral requirement.',
    ],
    eligibilityCriteria: [
      'Any individual above 18 years of age.',
      'At least 8th standard pass for projects costing above ₹10 Lakh in manufacturing or above ₹5 Lakh in service sector.',
      'Only new micro-enterprise projects are eligible; existing units not eligible.',
      'Special category beneficiaries (SC, ST, OBC, Minorities, Women, Ex-servicemen, Differently-abled) receive 35% rural subsidy.',
    ],
    applicationProcess: [
      'Step 1: Register on the KVIC / PMEGP e-Portal (kviconline.gov.in).',
      'Step 2: Fill online Common Application Form and upload Aadhaar, Caste, and DPR.',
      'Step 3: Application verified by District Industries Centre (DIC) / KVIC Task Force.',
      'Step 4: Forwarding of scrutinized dossier to preferred financing bank.',
      'Step 5: Sanction of loan, disbursement of subsidy into TDR account, and EDP training.',
    ],
    faqs: [
      {
        question: 'What is the maximum project cost eligible under PMEGP?',
        answer: 'The maximum cost of the project/unit eligible for subsidy is ₹50 Lakhs in the manufacturing sector and ₹20 Lakhs in the service sector.',
      },
      {
        question: 'Who provides the subsidy under PMEGP?',
        answer: 'The capital subsidy is routed through KVIC as the nodal agency directly into the beneficiary bank loan account.',
      },
      {
        question: 'Is collateral security required for PMEGP loan?',
        answer: 'No collateral security or third-party guarantee is required for loans up to ₹10 Lakhs under CGTMSE coverage.',
      },
    ],
    sourcesAndReferences: [
      { title: 'KVIC Online Official Portal', url: 'https://www.kviconline.gov.in' },
      { title: 'Ministry of MSME Official Website', url: 'https://msme.gov.in' },
    ],
  },
  {
    id: 'pm-vishwakarma',
    code: 'PM_VISHWAKARMA',
    nameEn: 'PM Vishwakarma Kaushal Samman',
    nameHi: 'प्रधानमंत्री विश्वकर्मा कौशल सम्मान योजना',
    ministryEn: 'Ministry of Micro, Small and Medium Enterprises',
    ministryHi: 'सूक्ष्म, लघु और मध्यम उद्यम मंत्रालय',
    descriptionEn: 'End-to-end holistic support for traditional artisans and craftspeople covering 18 trades with toolkits and collateral-free loans.',
    descriptionHi: '18 पारंपरिक व्यवसायों में लगे कारीगरों और शिल्पकारों के लिए टूलकिट और 5% रियायती ब्याज पर ऋण।',
    compatibilityPercentage: 91.2,
    categoryBadge: 'ARTISAN DEDICATED',
    tags: ['Artisans & Craftsmen', 'Skill Development', 'Financial Support'],
    financials: {
      grantSubsidyPercentage: 15,
      maxGrantAmount: 15000,
      loanPercentage: 85,
      promoterMarginPercentage: 0,
      subsidizedInterestRate: 5.0,
      moratoriumPeriodMonths: 3,
      collateralRequired: false,
    },
    requiredDocuments: ['DOC_AADHAAR', 'DOC_CASTE'],
    verifiedDocuments: ['DOC_AADHAAR', 'DOC_CASTE'],
    missingDocuments: [],
    eligibilityHighlights: [
      '₹15,000 free modern toolkit e-voucher grant',
      '₹1,00,000 first tranche + ₹2,00,000 second tranche @ 5% flat rate',
      '5-day basic skill training with ₹500/day stipend',
    ],
    nodalAgency: 'District Industries Centre (DIC) & Nodal Banks',
    benefits: [
      'Recognition as Vishwakarma through PM Vishwakarma Certificate and ID Card.',
      'Skill upgradation with basic 5-7 days training with stipend of ₹500/day.',
      'Toolkit incentive e-voucher worth ₹15,000 to purchase modern tools.',
      'Collateral-free enterprise loan: Tranche 1 up to ₹1,00,000 and Tranche 2 up to ₹2,00,000 at concessional interest rate of 5%.',
      'Incentive for digital transactions up to ₹100 per month.',
    ],
    eligibilityCriteria: [
      'Artisan or craftsperson working with hands and tools in one of the 18 specified family-based traditional trades.',
      'Minimum age of 18 years on the date of application.',
      'Should not have availed loans under similar credit-based schemes like PMEGP, PM SVANidhi, Mudra in past 5 years.',
      'Only one member per family is eligible to receive benefits.',
    ],
    applicationProcess: [
      'Step 1: Free biometric registration at nearest Common Services Centre (CSC).',
      'Step 2: Gram Panchayat / ULB level verification of trade authenticity.',
      'Step 3: District Implementation Committee (DIC) screening and approval.',
      'Step 4: Issuance of PM Vishwakarma digital ID and toolkit e-voucher.',
      'Step 5: Completion of basic training and direct credit disbursement into bank account.',
    ],
    faqs: [
      {
        question: 'Which trades are eligible under PM Vishwakarma?',
        answer: '18 traditional trades including Carpenter, Blacksmith, Potter, Sculptor, Cobbler, Tailor, Basket Weaver, Barber, Washerman, and others.',
      },
      {
        question: 'What is the interest rate charged on PM Vishwakarma loans?',
        answer: 'The interest rate charged to the beneficiary is fixed at a concessional rate of 5% per annum, with the remaining interest subvention funded by the Government of India.',
      },
    ],
    sourcesAndReferences: [
      { title: 'PM Vishwakarma Official Portal', url: 'https://pmvishwakarma.gov.in' },
      { title: 'Ministry of MSME Portal', url: 'https://msme.gov.in' },
    ],
  },
  {
    id: 'pm-svanidhi',
    code: 'PM_SVANIDHI',
    nameEn: 'PM Street Vendor’s AtmaNirbhar Nidhi (PM SVANidhi)',
    nameHi: 'पीएम स्ट्रीट वेंडर्स आत्मनिर्भर निधि (पीएम स्वनिधि)',
    ministryEn: 'Ministry of Housing and Urban Affairs (MoHUA)',
    ministryHi: 'आवासन और शहरी कार्य मंत्रालय',
    descriptionEn: 'Affordable collateral-free working capital loan facility to street vendors, thela operators, and small urban stalls.',
    descriptionHi: 'रेहड़ी-पटरी वालों और ठेले वालों के लिए किफायती कार्यशील पूंजी ऋण एवं 7% ब्याज सब्सिडी।',
    compatibilityPercentage: 88.0,
    categoryBadge: 'MICRO WORKING CAPITAL',
    financials: {
      grantSubsidyPercentage: 7,
      maxGrantAmount: 3500,
      loanPercentage: 100,
      promoterMarginPercentage: 0,
      subsidizedInterestRate: 7.0,
      moratoriumPeriodMonths: 0,
      collateralRequired: false,
    },
    requiredDocuments: ['DOC_AADHAAR'],
    verifiedDocuments: ['DOC_AADHAAR'],
    missingDocuments: [],
    eligibilityHighlights: [
      'Tranche 1: ₹10,000 -> Tranche 2: ₹20,000 -> Tranche 3: ₹50,000',
      '7% interest subsidy credited directly to bank account',
      'Up to ₹1,200/year cashback on digital UPI transactions',
    ],
    nodalAgency: 'Urban Local Bodies (ULB) & Scheduled Commercial Banks',
  },
  {
    id: 'pm-mudra-kishore',
    code: 'MUDRA_KISHORE',
    nameEn: 'Pradhan Mantri Mudra Yojana (Kishore Window)',
    nameHi: 'प्रधानमंत्री मुद्रा योजना (किशोर श्रेणी)',
    ministryEn: 'Department of Financial Services (DFS), MoF',
    ministryHi: 'वित्तीय सेवाएं विभाग, वित्त मंत्रालय',
    descriptionEn: 'Term loan and working capital credit from ₹50,000 to ₹5,00,000 for expanding existing small businesses and workshops.',
    descriptionHi: 'मौजूदा व्यवसायों और कार्यशालाओं के विस्तार हेतु ₹50,000 से ₹5,00,000 तक का रियायती ऋण।',
    compatibilityPercentage: 85.5,
    categoryBadge: 'BUSINESS EXPANSION',
    financials: {
      grantSubsidyPercentage: 0,
      maxGrantAmount: 0,
      loanPercentage: 90,
      promoterMarginPercentage: 10,
      subsidizedInterestRate: 9.25,
      moratoriumPeriodMonths: 6,
      collateralRequired: false,
    },
    requiredDocuments: ['DOC_AADHAAR', 'DOC_INCOME'],
    verifiedDocuments: ['DOC_AADHAAR', 'DOC_INCOME'],
    missingDocuments: [],
    eligibilityHighlights: [
      'Loans between ₹50,000 and ₹5,00,000',
      'Zero third-party collateral or guarantee needed',
      'Pre-approved Mudra debit card for raw material purchases',
    ],
    nodalAgency: 'All Public Sector & Regional Rural Banks (RRBs)',
  },
  {
    id: 'stand-up-india',
    code: 'STAND_UP_INDIA',
    nameEn: 'Stand-Up India Scheme for Women & SC/ST',
    nameHi: 'स्टैंड-अप इंडिया योजना (महिला एवं अनुसूचित जाति/जनजाति)',
    ministryEn: 'Department of Financial Services, MoF',
    ministryHi: 'वित्तीय सेवाएं विभाग, वित्त मंत्रालय',
    descriptionEn: 'Bank loans between ₹10 Lakh and ₹1 Crore for establishing greenfield enterprises in manufacturing, services, or agri-allied trade.',
    descriptionHi: 'विनिर्माण, सेवा या व्यापार में नए उद्यम लगाने के लिए ₹10 लाख से ₹1 करोड़ तक का बैंक ऋण।',
    compatibilityPercentage: 82.0,
    categoryBadge: 'HIGH CAPITAL VENTURE',
    financials: {
      grantSubsidyPercentage: 15,
      maxGrantAmount: 1500000,
      loanPercentage: 75,
      promoterMarginPercentage: 10,
      subsidizedInterestRate: 8.75,
      moratoriumPeriodMonths: 18,
      collateralRequired: false,
    },
    requiredDocuments: ['DOC_AADHAAR', 'DOC_CASTE', 'DOC_INCOME', 'DOC_MARKSHEET'],
    verifiedDocuments: ['DOC_AADHAAR', 'DOC_CASTE', 'DOC_INCOME', 'DOC_MARKSHEET'],
    missingDocuments: [],
    eligibilityHighlights: [
      '₹10 Lakh to ₹100 Lakh loan window',
      'Exclusive for SC/ST and Women entrepreneurs',
      'Credit guarantee fund support via NCGTC',
    ],
    nodalAgency: 'SIDBI & Scheduled Commercial Banks',
  },
  {
    id: 'post-matric-scholarship',
    code: 'PMS_OBC_SC',
    nameEn: 'Post-Matric Scholarship for OBC & EBC Students',
    nameHi: 'पोस्ट-मैट्रिक छात्रवृत्ति योजना (ओबीसी एवं ईबीसी)',
    ministryEn: 'Ministry of Social Justice and Empowerment',
    ministryHi: 'सामाजिक न्याय और अधिकारिता मंत्रालय',
    descriptionEn: 'Complete tuition fee waiver and monthly maintenance allowance for students pursuing higher secondary and degree education.',
    descriptionHi: 'उच्चतर माध्यमिक व स्नातक छात्रों के लिए पूर्ण शिक्षण शुल्क प्रतिपूर्ति एवं मासिक भत्ता।',
    compatibilityPercentage: 79.0,
    categoryBadge: 'SCHOLARSHIP & EDUCATION',
    financials: {
      grantSubsidyPercentage: 100,
      maxGrantAmount: 48000,
      loanPercentage: 0,
      promoterMarginPercentage: 0,
      collateralRequired: false,
    },
    requiredDocuments: ['DOC_AADHAAR', 'DOC_CASTE', 'DOC_INCOME', 'DOC_MARKSHEET'],
    verifiedDocuments: ['DOC_AADHAAR', 'DOC_CASTE', 'DOC_INCOME', 'DOC_MARKSHEET'],
    missingDocuments: [],
    eligibilityHighlights: [
      '100% tuition and institutional fee reimbursement',
      'Direct Benefit Transfer (DBT) to student Aadhaar-seeded bank account',
      'Annual parental income limit $\\le ₹2.5$ Lakh',
    ],
    nodalAgency: 'National Scholarship Portal (NSP) / State Welfare Dept',
  },
];

export const TRADE_PRESETS = [
  { nameEn: 'Farming & Dairy', nameHi: 'खेती व डेयरी', icon: '🌾', category: 'Agriculture' },
  { nameEn: 'Terracotta Potter', nameHi: 'कुम्हार व शिल्पकार', icon: '🏺', category: 'Artisan' },
  { nameEn: 'Street Vendor & Thela', nameHi: 'रेहड़ी-पटरी व ठेला', icon: '🛒', category: 'Micro Enterprise' },
  { nameEn: 'Tailoring & Handloom', nameHi: 'सिलाई व हथकरघा', icon: '🧵', category: 'Textiles' },
  { nameEn: 'Food Stall & Catering', nameHi: 'खान-पान व ढाबा', icon: '🍲', category: 'Services' },
  { nameEn: 'Carpentry & Woodwork', nameHi: 'बढ़ई व काष्ठकला', icon: '🪚', category: 'Artisan' },
  { nameEn: 'Mechanic & EV Repair', nameHi: 'मैकेनिक व वाहन मरम्मत', icon: '🛵', category: 'Services' },
  { nameEn: 'Student & Scholar', nameHi: 'छात्रवृत्ति व पढ़ाई', icon: '📚', category: 'Education' },
  { nameEn: 'Solar & Renewable Energy', nameHi: 'सौर एवं नवीकरणीय ऊर्जा', icon: '☀️', category: 'Energy & Research' },
  { nameEn: 'Blacksmith / Lohar', nameHi: 'लोहार व धातु शिल्प', icon: '🔨', category: 'Artisan' },
  { nameEn: 'Basket & Bamboo Weaver', nameHi: 'बांस व टोकरी बुनकर', icon: '🧺', category: 'Artisan' },
  { nameEn: 'Leather & Footwear', nameHi: 'चर्मकार व जूता निर्माण', icon: '👞', category: 'Artisan' },
  { nameEn: 'Beauty Parlour & Salon', nameHi: 'ब्यूटी पार्लर व सैलून', icon: '💇', category: 'Services' },
];
