import { SchemeMatch } from '../types';

export const MOCK_SCHEMES: SchemeMatch[] = [
  {
    id: 'pm-egp',
    code: 'PMEGP',
    nameEn: "Prime Minister's Employment Generation Programme (PMEGP)",
    nameHi: "प्रधानमंत्री रोजगार सृजन कार्यक्रम (PMEGP)",
    ministryEn: 'Ministry of MSME / KVIC',
    ministryHi: 'सूक्ष्म, लघु एवं मध्यम उद्यम मंत्रालय (KVIC)',
    descriptionEn: 'Credit-linked capital subsidy scheme designed for setting up new micro-enterprises in manufacturing and services sector.',
    descriptionHi: 'विनिर्माण एवं सेवा क्षेत्रों में नए सूक्ष्म उद्यम स्थापित करने के लिए क्रेडिट-लिंक्ड पूंजी सब्सिडी योजना।',
    compatibilityPercentage: 94.5,
    categoryBadge: 'TOP SUBSIDY MATCH',
    financials: {
      grantSubsidyPercentage: 35,
      maxGrantAmount: 1750000,
      loanPercentage: 60,
      promoterMarginPercentage: 5,
      subsidizedInterestRate: 8.5,
      moratoriumPeriodMonths: 6,
      collateralRequired: false,
    },
    requiredDocuments: ['DOC_AADHAAR', 'DOC_CASTE', 'DOC_RURAL', 'DOC_INCOME'],
    verifiedDocuments: ['DOC_AADHAAR', 'DOC_CASTE', 'DOC_INCOME'],
    missingDocuments: ['DOC_RURAL'],
    eligibilityHighlights: [
      '35% direct non-refundable capital grant for rural OBC/SC/ST/Women',
      'Only 5% beneficiary own margin required',
      '100% collateral-free under CGTMSE cover',
    ],
    nodalAgency: 'Khadi & Village Industries Commission (KVIC) / DIC Gorakhpur',
  },
  {
    id: 'pm-vishwakarma',
    code: 'PM_VISHWAKARMA',
    nameEn: 'PM Vishwakarma Kaushal Samman',
    nameHi: 'प्रधानमंत्री विश्वकर्मा कौशल सम्मान योजना',
    ministryEn: 'Ministry of Micro, Small and Medium Enterprises',
    ministryHi: 'सूक्ष्म, लघु और मध्यम उद्यम मंत्रालय',
    descriptionEn: 'End-to-end holistic support for traditional artisans and craftspeople covering 18 trades with toolkits and collateral-free loans.',
    descriptionHi: '18 पारंपरिक व्यवसायों में लगे कारीगरों और शिल्पकारों के लिए टूलकिट और 5% रियायती ब्याज पर ऋण।',
    compatibilityPercentage: 91.2,
    categoryBadge: 'ARTISAN DEDICATED',
    financials: {
      grantSubsidyPercentage: 15,
      maxGrantAmount: 15000,
      loanPercentage: 85,
      promoterMarginPercentage: 0,
      subsidizedInterestRate: 5.0,
      moratoriumPeriodMonths: 3,
      collateralRequired: false,
    },
    requiredDocuments: ['DOC_AADHAAR', 'DOC_CASTE'],
    verifiedDocuments: ['DOC_AADHAAR', 'DOC_CASTE'],
    missingDocuments: [],
    eligibilityHighlights: [
      '₹15,000 free modern toolkit e-voucher grant',
      '₹1,00,000 first tranche + ₹2,00,000 second tranche @ 5% flat rate',
      '5-day basic skill training with ₹500/day stipend',
    ],
    nodalAgency: 'District Industries Centre (DIC) & Nodal Banks',
  },
  {
    id: 'pm-svanidhi',
    code: 'PM_SVANIDHI',
    nameEn: 'PM Street Vendor’s AtmaNirbhar Nidhi (PM SVANidhi)',
    nameHi: 'पीएम स्ट्रीट वेंडर्स आत्मनिर्भर निधि (पीएम स्वनिधि)',
    ministryEn: 'Ministry of Housing and Urban Affairs (MoHUA)',
    ministryHi: 'आवासन और शहरी कार्य मंत्रालय',
    descriptionEn: 'Affordable collateral-free working capital loan facility to street vendors, thela operators, and small urban stalls.',
    descriptionHi: 'रेहड़ी-पटरी वालों और ठेले वालों के लिए किफायती कार्यशील पूंजी ऋण एवं 7% ब्याज सब्सिडी।',
    compatibilityPercentage: 88.0,
    categoryBadge: 'MICRO WORKING CAPITAL',
    financials: {
      grantSubsidyPercentage: 7,
      maxGrantAmount: 3500,
      loanPercentage: 100,
      promoterMarginPercentage: 0,
      subsidizedInterestRate: 7.0,
      moratoriumPeriodMonths: 0,
      collateralRequired: false,
    },
    requiredDocuments: ['DOC_AADHAAR'],
    verifiedDocuments: ['DOC_AADHAAR'],
    missingDocuments: [],
    eligibilityHighlights: [
      'Tranche 1: ₹10,000 -> Tranche 2: ₹20,000 -> Tranche 3: ₹50,000',
      '7% interest subsidy credited directly to bank account',
      'Up to ₹1,200/year cashback on digital UPI transactions',
    ],
    nodalAgency: 'Urban Local Bodies (ULB) & Scheduled Commercial Banks',
  },
  {
    id: 'pm-mudra-kishore',
    code: 'MUDRA_KISHORE',
    nameEn: 'Pradhan Mantri Mudra Yojana (Kishore Window)',
    nameHi: 'प्रधानमंत्री मुद्रा योजना (किशोर श्रेणी)',
    ministryEn: 'Department of Financial Services (DFS), MoF',
    ministryHi: 'वित्तीय सेवाएं विभाग, वित्त मंत्रालय',
    descriptionEn: 'Term loan and working capital credit from ₹50,000 to ₹5,00,000 for expanding existing small businesses and workshops.',
    descriptionHi: 'मौजूदा व्यवसायों और कार्यशालाओं के विस्तार हेतु ₹50,000 से ₹5,00,000 तक का रियायती ऋण।',
    compatibilityPercentage: 85.5,
    categoryBadge: 'BUSINESS EXPANSION',
    financials: {
      grantSubsidyPercentage: 0,
      maxGrantAmount: 0,
      loanPercentage: 90,
      promoterMarginPercentage: 10,
      subsidizedInterestRate: 9.25,
      moratoriumPeriodMonths: 6,
      collateralRequired: false,
    },
    requiredDocuments: ['DOC_AADHAAR', 'DOC_INCOME'],
    verifiedDocuments: ['DOC_AADHAAR', 'DOC_INCOME'],
    missingDocuments: [],
    eligibilityHighlights: [
      'Loans between ₹50,000 and ₹5,00,000',
      'Zero third-party collateral or guarantee needed',
      'Pre-approved Mudra debit card for raw material purchases',
    ],
    nodalAgency: 'All Public Sector & Regional Rural Banks (RRBs)',
  },
  {
    id: 'stand-up-india',
    code: 'STAND_UP_INDIA',
    nameEn: 'Stand-Up India Scheme for Women & SC/ST',
    nameHi: 'स्टैंड-अप इंडिया योजना (महिला एवं अनुसूचित जाति/जनजाति)',
    ministryEn: 'Department of Financial Services, MoF',
    ministryHi: 'वित्तीय सेवाएं विभाग, वित्त मंत्रालय',
    descriptionEn: 'Bank loans between ₹10 Lakh and ₹1 Crore for establishing greenfield enterprises in manufacturing, services, or agri-allied trade.',
    descriptionHi: 'विनिर्माण, सेवा या व्यापार में नए उद्यम लगाने के लिए ₹10 लाख से ₹1 करोड़ तक का बैंक ऋण।',
    compatibilityPercentage: 82.0,
    categoryBadge: 'HIGH CAPITAL VENTURE',
    financials: {
      grantSubsidyPercentage: 15,
      maxGrantAmount: 1500000,
      loanPercentage: 75,
      promoterMarginPercentage: 10,
      subsidizedInterestRate: 8.75,
      moratoriumPeriodMonths: 18,
      collateralRequired: false,
    },
    requiredDocuments: ['DOC_AADHAAR', 'DOC_CASTE', 'DOC_INCOME', 'DOC_MARKSHEET'],
    verifiedDocuments: ['DOC_AADHAAR', 'DOC_CASTE', 'DOC_INCOME', 'DOC_MARKSHEET'],
    missingDocuments: [],
    eligibilityHighlights: [
      '₹10 Lakh to ₹100 Lakh loan window',
      'Exclusive for SC/ST and Women entrepreneurs',
      'Credit guarantee fund support via NCGTC',
    ],
    nodalAgency: 'SIDBI & Scheduled Commercial Banks',
  },
  {
    id: 'post-matric-scholarship',
    code: 'PMS_OBC_SC',
    nameEn: 'Post-Matric Scholarship for OBC & EBC Students',
    nameHi: 'पोस्ट-मैट्रिक छात्रवृत्ति योजना (ओबीसी एवं ईबीसी)',
    ministryEn: 'Ministry of Social Justice and Empowerment',
    ministryHi: 'सामाजिक न्याय और अधिकारिता मंत्रालय',
    descriptionEn: 'Complete tuition fee waiver and monthly maintenance allowance for students pursuing higher secondary and degree education.',
    descriptionHi: 'उच्चतर माध्यमिक व स्नातक छात्रों के लिए पूर्ण शिक्षण शुल्क प्रतिपूर्ति एवं मासिक भत्ता।',
    compatibilityPercentage: 79.0,
    categoryBadge: 'SCHOLARSHIP & EDUCATION',
    financials: {
      grantSubsidyPercentage: 100,
      maxGrantAmount: 48000,
      loanPercentage: 0,
      promoterMarginPercentage: 0,
      collateralRequired: false,
    },
    requiredDocuments: ['DOC_AADHAAR', 'DOC_CASTE', 'DOC_INCOME', 'DOC_MARKSHEET'],
    verifiedDocuments: ['DOC_AADHAAR', 'DOC_CASTE', 'DOC_INCOME', 'DOC_MARKSHEET'],
    missingDocuments: [],
    eligibilityHighlights: [
      '100% tuition and institutional fee reimbursement',
      'Direct Benefit Transfer (DBT) to student Aadhaar-seeded bank account',
      'Annual parental income limit $\\le ₹2.5$ Lakh',
    ],
    nodalAgency: 'National Scholarship Portal (NSP) / State Welfare Dept',
  },
];

export const TRADE_PRESETS = [
  { nameEn: 'Farming & Dairy', nameHi: 'खेती व डेयरी', icon: '🌾', category: 'Agriculture' },
  { nameEn: 'Terracotta Potter', nameHi: 'कुम्हार व शिल्पकार', icon: '🏺', category: 'Artisan' },
  { nameEn: 'Street Vendor & Thela', nameHi: 'रेहड़ी-पटरी व ठेला', icon: '🛒', category: 'Micro Enterprise' },
  { nameEn: 'Tailoring & Handloom', nameHi: 'सिलाई व हथकरघा', icon: '🧵', category: 'Textiles' },
  { nameEn: 'Food Stall & Catering', nameHi: 'खान-पान व ढाबा', icon: '🍲', category: 'Services' },
  { nameEn: 'Carpentry & Woodwork', nameHi: 'बढ़ई व काष्ठकला', icon: '🪚', category: 'Artisan' },
  { nameEn: 'Mechanic & EV Repair', nameHi: 'मैकेनिक व वाहन मरम्मत', icon: '🛵', category: 'Services' },
  { nameEn: 'Student & Scholar', nameHi: 'छात्रवृत्ति व पढ़ाई', icon: '📚', category: 'Education' },
  { nameEn: 'Blacksmith / Lohar', nameHi: 'लोहार व धातु शिल्प', icon: '🔨', category: 'Artisan' },
  { nameEn: 'Basket & Bamboo Weaver', nameHi: 'बांस व टोकरी बुनकर', icon: '🧺', category: 'Artisan' },
  { nameEn: 'Leather & Footwear', nameHi: 'चर्मकार व जूता निर्माण', icon: '👞', category: 'Artisan' },
  { nameEn: 'Beauty Parlour & Salon', nameHi: 'ब्यूटी पार्लर व सैलून', icon: '💇', category: 'Services' },
];
